spring.application.name=sample02-repository-pattern
server.port=8002
spring.profiles.active=memory
spring.datasource.url=jdbc:h2:mem:sample02;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
